#!bin/bash
if [ -s "/data/data/com.termux/files/usr/etc/dets" ]
then
. /data/data/com.termux/files/usr/etc/dets
. /data/data/com.termux/files/usr/etc/dets.n
else
bash files/lgn
bash start
fi

#installing basic programs

python --version &> h
t=$(echo $?)
if [ $t = 0 ]
then
rm h
else
echo "installing python"
pkg install python
rm h
fi
if [ -s "files/do-not-remove" ]
then
printf ""
else
clear
echo "Installing the necessary packages"
python3 files/prereqs.py
echo "DO NOT REMOVE THIS FILE" > files/do-not-remove
fi

#Program install end
read -p "Article Link > " lnk
fnm=${usrn}-${fo}
read -p "Focused Keyword > " fkey
read -p "2nd Focus Keyword > " skey
h(){
cat <<- EOF
lnk = ("${lnk}")
fnm = ("${fnm}")
fkey = ("${fkey}")
skey = ("${skey}")
EOF
}
fn=${fnm}.docx
h > files/data.py
python3 files/ArticlescraperURL.py
if [ -d "articles" ]
then
if [ -s "$fn" ]
then
mv $fn articles
fi
else
mkdir articles
if [ -s "$fn" ]
then
mv $fn articles
fi
fi
rm files/data.py
echo fo="$(( $fo + 1 ))" > /data/data/com.termux/files/usr/etc/dets.n
exit 0
